version: '3.2'

services:

  collector:
    image: "stackrox/collector:${COLLECTOR_TAG}"
    environment:
    - "GRPC_SERVER=grpc-server:9999"
    - 'COLLECTOR_CONFIG={"syscalls":["accept","connect","execve","fork","clone","close","shutdown","socket"]}'
    restart: always
    privileged: true
    networks:
    - collector
    volumes:
    - /var/run/docker.sock:/host/var/run/docker.sock:ro
    - /proc:/host/proc:ro
    - /sys/module:/host/sys/module:ro
    - /dev:/host/dev:ro

  grpc-server:
    image: stackrox/grpc-server:2.3.15.0-90-g319c5f1530
    ports:
    - "9999"
    networks:
    - collector
    volumes:
    - /tmp:/tmp:rw

networks:
  collector:
